apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  namespace: business
  labels:
    app: data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
      annotations:
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/json.add_error_key: "true"
        co.elastic.logs/json.message_key: "message"
        co.elastic.logs/json.overwrite_keys: "true"
    spec:
      containers:
        - name: data-service
          image: ion21/data-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: argo
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: demo-kafka-bootstrap.messaging.svc:9092
            - name: APP_KAFKA_TOPIC
              value: product-topic
            - name: MYSQL_URL
              value: "jdbc:mysql://moco-mysql-primary.data.svc:3306/micro_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
            - name: KEYCLOAK_SERVER_URL
              value: https://auth.icode.mywire.org
            - name: KEYCLOAK_REALM
              value: rsk
            - name: KEYCLOAK_ISSUER
              value: https://auth.icode.mywire.org/realms/rsk
            - name: KEYCLOAK_JWK_SET_URI
              value: https://auth.icode.mywire.org/realms/rsk/protocol/openid-connect/certs
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-app
                  key: WRITABLE_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-app
                  key: WRITABLE_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: business
spec:
  type: ClusterIP
  selector:
    app: data-service
  ports:
    - port: 8081
      targetPort: 8081
