fullnameOverride: kong

ingressController:
  enabled: false

env:
  database: "off"

dblessConfig:
  configMap: kong-declarative

proxy:
  type: ClusterIP

admin:
  enabled: false

manager:
  enabled: false