apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - job-config-cli.yaml

configMapGenerator:
  - name: keycloak-realm-rsk
    files:
      - realm/rsk.yaml

generatorOptions:
  disableNameSuffixHash: true
