apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: strimzi-cluster-operator
  namespace: messaging
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  podMetricsEndpoints:
    - port: http
      path: /metrics