---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgB388+TOSDFMzoVLH//81iGLlrH9HN4P6uevc8vmc8JqbOnXWjGaGzNnuQDqMUw1TwtQLX5VWJ8tSMV9EKUJNR7ddy1jGF5ccXQm1KFknqD8V2xh1/i3VYAhLp75eByoC2j1ggWKLAOztV+kGDfbA9o8UOJUkf8uRK1oIpUniZb80E3l8rb3lYdbKh91G2RLjRYUyfA1JJ73ALkGUU1YrD0hbpPax8AqVSwAVGAh1THt21yPjpdF5exUwoSNZy2Dq0MGbq8XRjxMf6u0s3LgjwT86KdYJR+kBSGaE9lJ2ubzALaxgAWGym0X2zusAjcN7D3SUN9VDjTh8ZapzYnffiIxLMYyxD8nhdwNrrExiHnxvyhYHmSUrbBWGHQpeIT+Ll6OpSSf29xEGqZz8vAL3xrzUpAZWIBTBE11lar6E80udw+506wMErVZSlpHuSbegA0RSZZ13TKwwV9ARTcAZAq5chttjDRAYoFfMyg5/0LFiyppBNYlrEB+OipFWS+tUeO6hXMiSJLma+g6pjcqMEwpddjVcKZB/heGif0Vv5MTbQp0I6nSuxCudyJcFX3janw2PXd6LGRtU+n7s1GOhroa4nO8frF9GHD/3Z5SLSrgVKWLyIvkm6SUBGEKVw5nCeFuczfxk1VkUPhguo9YMP0WCoHYVBFrURKVMlplDt2JZCKegKuOF6L55nF+caPH810oKkfHk0suA==
  template:
    metadata:
      name: keycloak-credentials
      namespace: crossplane-system
    type: kubernetes.io/basic-auth
