---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgADBFVquI/zbh9UbcsYifLF5bnK95Do8Dmd/GONtAUEgkH2fM4OaH3CNLAV98Wf34hF5oiXZy7iGEkHI6Fkua/6MExW39noS6CYsFU+iPRcZqD/ufSUDq1xJXM+Tmgz+i/xmc7GA19EMt8ZpPdygykR2IjyqaWh0WJRIKTdnlG9NmLQuaQD6PGQbmlEc9XMQmEDRZqRqB223YKZhTnkeUwxBPO3WjCR7YEJna9qqlw6aSZsJaT2C7lR1AFqvOcWRFzjF9qq77QeN17Gu95sVksaSzFyqSESk4yWNCtee41vlOaY//a2ND2bfqPKpLJMjSknnbXOW/wLEClwNnhceGD+IQ9sOfvv+UxX1bYK3mG9Mi374tBYEB+biV5gmxA5h6uPRU85htxDoff7zAY0CxIYwgVVC/ZzNO62wdf/lMueqqdBy9wjgFB4XtxCu5sF4gGEJ6YEOlcGP/W4tzOCg8lQ9/3ZcEMLZM6/rtwhqb6dYaiak+n29MIilh3AJTOKMLIgyk4wkAACbn+1x2kct5cF+7oC86dsQP+XMW3Rxaq89I67tNr/OzEZaGE0pbZnUmuV3MhneRJtL+O2XYL6e5/3VYyqFu5Rkuy8yAf5bFeUfqlavXySbCDWVGNjrDP0allA0dtZNxdWTlvDfQsO8fgMfTZ84vUStIHC3H7iZKJP9TwR+3+KgsQObGVuiZAW4sWd1LZcIO2RYqnzBUTbgzEI9lAQSETuwGoETLa6evS/aZNzeSq5pXFbf2KKbS7bR7R4jeb5bgsF8OBC9FSgeT1GnBOS1UhB4olJvgsAUQOwWDlIm2z9oiSZGgjeEvygk6UEPDSfI1eo0oJHJfRePG0bqe4MX9honxTzDdZNJV3h22dPYogqTYkCLHFpuV5jGWrEfXfY5MbL7DaufzZso0vnoS1L1WKWkTmEG05cpqtFGYGWTDkODUShUhJsoaAGH6xqh6ygWqkYFRyWLGE/DBDvHkKQo4kFoex0tD5TQjUCUNlJuA==
  template:
    metadata:
      name: keycloak-credentials
      namespace: crossplane-system
    type: opaque
