apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: crossplane-system
type: opaque
stringData:
  credentials: |
    {
      "client_id": "admin-cli",
      "username": "<din secret keycloak-initial-admin>",
      "password": "<din secret keycloak-initial-admin>",
      "url": "http://keycloak-service.auth.svc:8080",
      "base_path": "",
      "realm": "master"
    }