---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBkYJcyB+yKg1xxZBsL7uP4r+32csiAXxMMk7Y/kg5OuuuDyR4bVyhUxYMVWXmhERWMP/C4FUGmKEtjXVXieMGO27VF1mfX94FdBIll27I6QKOiLH9J3eE9y70yEevmUXw3YSQrCCH01LA+I1OTrKYGuIv2fqFseioSaRjh1r9Q5jbBLpXSHrCiisS+J7FNoH0oNLZy+cRO7+shYLM7648Go9dVvci6or7/rBZWQElLrqwGC3XCOfeJowXIEvzzKyI3Nz6AmzCYMZHE37ek5VYGYtowFQJyp0CZc73vBxOlag+D3JomL62YozQa+wAMh7PMXntt4rYeu8fRvaWiJJ04y6K7lQMXSoJvyNDa+ic+8aNQAUmhns9FL2qR14AEh62D0SfmjRqctVWBbepnoms8yY6PNZpMDAURvFFF2vuVW/d5PYetmaDfTjiZrObG0xNx8kVFouApccESLBstC5qza5Bh8Q80w7HomnXnVAHz4q3KPUIA3puRZeqkmYJiihGL8y2YMFYFwrLtMKHJW6oNRLf76iyWXnDlCOxVAEHt7nO+cKug0yrqi3tmHBYLMu3N1IwuwecKZoxrdgOFBML+uU7Di1+BIsAqXa9TEXp7tzGccULC4qsU2ZB18IzNyL6battY9aB3sQja9KO9C7zeB5FA6tn9ADw/P33WvAym56sUCls4PIgf9MqWXRrd6BElsxxftt5pof4KWOYTv/zv9A==
    admin-user: AgCK4CnDR7OKuH/K8e91Wl0Hohen8KyucW95VIOI4Ol6T6L7Q7xbBkGWiFEfDd41aRNSGuuu8kkazrZTCYYWmrsSkmzgCq8pdRbjIR4kshRK2VFHpFC+hS96VloY0zV7P9DFLXceS1hoIfcol4HmNu9sE9acTPLofcXwK/xLG1v5KO5EyNSf+0apXzM4qM4Ub9rE8ACWi9AB7XVg+toUf17ZeHlh0Hhd0rI5LwGcOseEdnDb7ozb3VTpd4KMW4Z2uc67FYyUVi129WbH6fMnhoSuN6XdGrI7Zu8u1qtCZ4KzonQQ7INicazSV+P5P1cXEXWnOEGlZzKWEXooZ6AR/YWVD7bz1NTJtPQVK59AzNUei7nbsGVNEcXWhq2uPSC4BQ7yObaGM8yLphrpDNRpNe2WQrb1DudiEs3sB5Va6sHxZe0R6SXL3nHwJ0joxC8kVcrzJFMkszNlh7LcGY4RHl+VXOjXbX6LXmEYzQ0nJjQm/OjSLHbceqd1deDs9wJcY9EOZ9TpmxNknFKhgY7FowlS0jdHUw1qFHLEh7mtRJRQ9phmfEJacR1ILXAmiXBH0CFTUVvIQ61/7DhwmXzYhz4eZ7G5tqtLux10W2UAL69gb6xmQ2gyYlhqA5zURjGuMm4qHT9avjFH/w8LIfvcXvMR84uba1BbgX+nPWi3GjxHOYxR+u/U3JKjOq7q7cPQlvsWQ06VOA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
