---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: data-service-db
  namespace: data
spec:
  encryptedData:
    password: AgBZKRvgqvSwFl8LnWBhb5JLyx65CSDB+zy8bHIX8lNC7DjB+JGav/XeE22LyJvNCeVRkDNsSFt7lZNpTakG2IaJlS5FY569KqlJC47FcfjEGvZBsvyATK6DxohEcOMq5Hjuwy29+Co9p82xwFXFLT9vkUcd8LXBfzfm4N3ccaInG7BAiemGnlJ3850XHR57Dy4QzS6tpT0dwha0X4vTXvTFmdNQzKo7oMeczYEL5syzTVok+xBxtPNWC5vqm/eRpOtSGDJipOzlgn+4lIoITXr1H/fkUMRPFv/YZP/TnthEdn4ioGFqHRI/5xnYQKgbfi55HY3+5SKbEmEbkeA+6RSyiwVD29jS+6fu3KaygEpnnwkHYDkCZcg0CQu+XJhxdO+rBJD/cuo7PIDqVuTc4uHhGJeHZk0KexWaejxIrsTlnT3Bne/TubgIZzX8iSi6tZ/SqWGcHIaDilFDn5W3B8AxKIqEyFJkidUKs3J7YnCR/3UdYgKlQv25urkgQjzVpK1qR9A+wsDqyWBbagKNNQthdfAUeij8mPIlM2g1SyByCLJOQaYLfGXcuuz1GWe0E86mi+tgaOb+XY94AhTK2tkB1kCAy6yNfRft4xha5ul2nnEfMK5HsexaMklwuB2IGusONcR0xbxNz7OjWU0PPJtHuSPTbeD1+fI8DmMpu1B7QZCeyNk4TK4HgxBUdEf1nCNe/ASERZfaVVtuxTasUbG0Ru4LFRD3pwxxulOvcHbVIA==
    username: AgBsErVrQ2Dwp5ECDv4mAysQvfNp3xYkBKGd1dvLmIsj+Oc7QrQpMqPkrj0M8ZsSarYXvxU6UwyCCbXfGlgkp4mVClxgNpi2IXSAmIpAq9Sf1VnpIPYF2KYHOvLZ4eN8PKl1zYo8V4unwF5aQqD/lbF3DwyQNA7bPf0MSwuhzEBl9Bn70J26iEYO4457ca58AxlLlx9ozMVz1Mf6k9p96CPm0QtLOeIqwa3GdvHyQgP9/rILlaRBF+Lx0dlv6JRk0hwgsQyD3Cshp4urwLGswhwg2u5ECMP5dAQBdrldm9cnphudnv8whL9d18Rrpqz8jRaS37/JmlAjtu7twlej0UabwcvRHCkF96ZQ111hrRRnnh2XWEj5x/XbNUwBYWrEzhRU8K8FWF8ZnAQWi8hr2noPjdiXV9O1Jl+Tz2tKVgnF+EexwzU74IduAV/qZP5KhAh3Bo+ecQ1NuQ4X8g/eWlmSXPl1iDBL4F1t128I+HJ8B773P3AQ7FO1O0Vs0a8kLcP5+Tlsjnw4H5o0VjkNzF3DSdeyOmy47gYqz/7eb02IUmOhVjrHUIWXsTThIei0Sz9951aUgWU3CB8rgsGVoFGPCw06IWo3wpasslT24MSXM/pijI3W4dAmm5iW1uXiasBFwMNZW6Q8kmXZUmxK0vy9wY0O5KPt7JQWisTkr04xzgXERWTUTPfmwpw9QoAGjuBrZ+RdM8Zn
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: business
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: business
      name: data-service-db
      namespace: data
    type: kubernetes.io/basic-auth
