---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-db
  namespace: data
spec:
  encryptedData:
    READ_PASSWORD: AgClP0+53LX6DOBwXhEjhfM5WJAs/XTa4bH8zPOyn/mQJ0zLoZfTPJrfM8+Mw25aI3Sv5PTxEbeaTI8zc9Yi5orYO6C/v06CJWm5NdwFbxcW5KfuGwchO5bFowYJ8Vqt4JPbYSDWs50r4pyG8EY3xISY9i/WnMMAbbJJmcweXu3AMg781SdeW67xPJiLJwbPDN+atf6mFUuVh+8UTExB6hWKEAyiBmr7+EaS8GiA7RuXtJlGykEbkxrrCrL7oILNGuvgXdV8UAtIEvZ+Bosk0xP7Z6Uw6A7S3O6kCNz2zcemL9n3DlqB5SFZwWJljnRgvoPfAxKS2UP9mdrw9wbL1VosGq6cWR0ID41zuEy+86zEmlwkPr/FvHWQQa10DxcyP68EHsXmOnJkp/RkSeP7cXXS0YuD/l126XzWCGXL/yEtxLonsv72/FRpr3RHbmnciWvxQ96Yc3s5fcGVWVCDoLgws7416ei5NfXMGBPqDC5HQqCV+oujOlt2lecc6x1gcwY6nvG3x5EVyWSJ22k4Dx0bDIU5pzTmKuckLJQQj0fgqJOc5a1fkbZYQD3gzmyFXkaI+i4Bmfc4whW1BCWmtvOZjdHzpPmBjiI46hjAMoOs5FotAeRa+H+yhMDnYKxEaubkDcnPmw0onybk80oRuRMir0KuWTlcz5CKUBjkygAxKj/dqxb/vXPSxq+odvzx+tMVxfcZZ5KaOD7/9tDYB0XacLc=
    READ_USER: AgALfy46Neis3vZNnZkPrFeSXlgrNOWbLR5Wql9/VEXoS2GwVtzXkIZ+tbKsjJqY5CEfGMt+saOiFIjW76am15rBvEA2YlHZzDuwe0d0Txm8cZBEkleDBvcvbIR0SBNKEYzvA7nm/Eg7fl9hW2dxxGYgpQigG6yyzuBBeUKT7YZ+DGLj3uVOqJpazre6kSKr8VH6dA26rbc2/BNkJ4kvZ+DQ3QsBfRBEpRyCiHPgmMVRM8VRVOpinqu0muICyFPR6pxMgQ9L8iS8fxcx1PRo0DNmLwk1cPZMnYVwEOV02qn+FQRatPVDZfudZWTKaCCa4KPbfcGHmgs/GV+kTosLP2NJ9fQz/1ZxBj0ktpYhTMDjzDUeF88jtwz2Ux9ysjzWUyDushOQjWWMgPsbWUnwPU27A22gotVkV6bu/FK3QhLcL/ieDsZX9PEPR/AYOdVAzaYxo+yEeU4qFGvwW36mh+45DQNlFORN+61fGYZulGaf1GwmGWrfpRykaB9oaT2VvucaFc99PGfopPuRv6V2ofIMuJL9hiYlR3/RVsUGbr8bLvQ19bKIESO7rSOSLW8DtfuILj+Wr+aNaLQ0WW2JpOiote7ma3i82iLufS/zCZySVxNkiBIeX/+7CjsEC6D+n53Dz4qZAQLT36J3epN6blIi5NO9R6RP23FFmrUCn6gXJVAwAaqzwLZC7IuK6lbIPXKhgodxMe3OIg==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: business
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: business
      name: external-db
      namespace: data
    type: Opaque
