---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-app
  namespace: data
spec:
  encryptedData:
    password: AgA2nphxcSNRJvF64f2FlQ5ad2XOzWdBKEb69cTbFdkstHREzpkQ+frabhlZBzOg8gG/Fg6Hj2XN59dR3Pch8FXJWxGEi2qcwwV0q5LoHqv+swOGWrIjZSS2NV4BuaMYlXUSnBdkzR0+5NrUnF3Rh7bMvkC0PKpWlkJ/nGWEMOXHBKVyY2D42j5PHtbPlpFpT/NN17As2R5rdaGOLcn7XPr9eq1TUerVApgFfVf0yFSINyR4AQvuZ/NC30s+sOOI2WLy8+fmU33M+Aee2ZBgqvIg5/E2S2mBJL1igV1w9AhVT1QUEZ7P5ioJ0J3oJafUPBwj6MtnYHAV7rYVkNK10wn6UcTyzVYHdsNJvb2Jm+EB1HRdvEErBpzGaTdUtski5Dw+XnfJffGvMWQSAZ9qPymj+7UxxmeuUJv06ifSdtGDLZist7MtALVWYw9g8lr2jTfaT8WGFcggX1cw3MBvgLPvFWYiXZ2ZuLCNAHWlv3phmmlCkHDzCxZ4mHdA+1LxzA+3/pmHMtX3x7WDDhr0V9xbiOrQHKG9DmJ2KpmQMrgbfPcGg1AI6MIg7BV7a5sMUp/ZB0atJj707qNVW+z3Yjn6UumrJTIrIVAlQlrepnyQ6ndXvm6T4KhzDmI1i2fexaFmzYF06jwqu6krlmN6BM1IIRl2iTrblk82d0g+lAefCr7IdhI3DTGIS6ieo8gURHUikxQksVMnNQsaTwK+57P60us=
    username: AgBcVqG+NS2m29vDPyh1kBXBcWWQ1Zinh0UiPwoFI8TSdoVvAXxm4oMQHw3Oq0jfrqwMajRfI2SWU8gh94VLNXIkSU5kYOCE9Qbrmy6cS7FEPp0+Sxz54J8ygyYA2wN3SYC1p7U9fs7XCNFZN1+/IEqHzNbXE83i1oTjKSkPB4fvjF/5tmdocSSOELICjyqfOpe5igKXSP5plYW/eyKVBilj650bcoKzrRsJSWjXwcAXcLRowaVEwzzuuUvxhTL0ACtBV6HEfWqTZlAJ3eBos8VvmukRUi+fVMS+tdXjgWp6MQYrjqxC0/stPZh98iuzq2MNUDzD26Vf1QJRA1Et/zZgHQrEz+9Z/DPyDPNdcjpx3XOchTUXBwhF9AoIxmKZC3/OGRvvvCkejQU1gXk+ndTq6pfl4FcZA4KeLiNlkqngjdLw9/NzvQMxfuUI0+Y0AD8SAvF/r/Igp+iexlbk43DvqNtP7qQ/LI2Kt3I929dKVlh0jf45YH2JXSt09udNsqxkgb4ME8CL9KdjVrtlpSnODMVUbP/PbPif8KcyxP/3h1zm1uSUQhpo5C2T6RgTHAqokNOzhxWIbXqShTD+KhVVe6mvbGVYqNPvZrjf/cPqXv2DY4vjttYSdlQzL23gbKrTK8nH/jA4zKmS3HGNuiaA1v4tvCoF5vZlHUVEqpS82YVzyukAFn2JcnLEOYCBTkeqzzmtCMmEjw==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: auth
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: auth
      name: keycloak-db-app
      namespace: data
    type: kubernetes.io/basic-auth
