---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-demo-password
  namespace: data
spec:
  encryptedData:
    password: AgAm4tcwf8ilEtA/krO+7hfx4ZI8UBCD2QTIhSEmrqFswBuj6fwIya4P/ufs4PsI8drpu6DT0NTT0Gau+ubxHneXrLUeXrP9iuNFTmcflR8oArvPgH6CjpwptRES/uXxgGEC2iEMaIgO2BMo8CDJc4iDJZ2j0PJRcGFCJCllX2bdcVr49lXYWjeJeK3uhGEP6V/RhQYKwk43mlyUYGn/TBMoh9JZ0tgXwfdXibcbeEDf4aM2J0xvqhMnVwfhouYK6KvsW0O2582qC3/MPebTnQnZF0X9Q014Bo9YC19Ak61/m0i7CqI5WIMAXNodT49Tmx4oteWC6z1QAO2z3x3Ildc/tdQDOVr4t49QFWdI/5f12Y7SLWZn/YT3Ih5oDgaifxuM9EZvcx7dHar3UXN31olfYDG70GiNTEXddwkPhp8Y5eLN1eJl+rF0LvJCoUmUMatiAmnVEZCkZ1uY4db5A0SAQE7w1JIfT479ncE+4UznZTUd4sal9AjXi6AELEFusV81K6K3G6fEUSawJ7A9FTx8eCepvjQ1QvLHn/TnsgpvWMDSEpx/dMThBNmw3HTMd3+DfwnmusKqhLCxzWeE7X2SkhaXlagZwMp/WSs4KQMTVXBUF7fVKBv4ISJtU6QyIMdZAYHTksX23cx/sk0N44oBqBaR2BgXZAnlyQlnWiz9tsNjmHdv43sLH4i4wwtJYa39a03xOrY9aVnqcMny
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: data
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: data
      name: mongo-demo-password
      namespace: data
    type: kubernetes.io/basic-auth
