---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-app
  namespace: business
spec:
  encryptedData:
    WRITABLE_PASSWORD: AgBTsNJhdaMVfOML87bHcr7tWltDSn7/nB4mPwNwVBNGUIjNr9R46Hs1WIQdJQ14YK2TkulW9DXRb8k47jn3evZVvKVRcLaTICid4dgCP0DaG+0W0XSAZliVdXeMlvw22EBV1SK6CWE3tbz3IddEVlJ29oLXtrrUuoF8bE5PXCVMRSvqeL917n2b5WAGgXpi0rLUYOLO/TQlYbeHGIoT8pE5aN5OVWUC9nbW/AhzXarf1fGRnf8BSkRPFyznBLpRSwFBY35864GFgq7dKlA+0fFG7aelP35rslqBnmcrJqTu2vQnFLOAqQ/L5SE6atKce7YZnEHFm43/alA9ezwjTHExwcaFJe6ShFuNMKdsembg9roO8PwQp/v83MHZmg+R/f79qLSgEo0TPIqinCMcoip2lPsJ294xgILgVEUFumv7bw5Y4xhqkjjH0qDLx0yhKQaEZU8d94IV+rqajhYdmQd3vDOSdnriAsug5j/3Pn07KVJTBByuI4oWpQjRm+EqHY9y0m2Y4EL4F5nXq/ipCl4uGO+RB4Ymw1xF+1imd80G4NNG+AObx+dZ33TNhQblP5plCZqVTxBkTgAxMTT5eywxcbfRZ/8fMPq6Ck7c3e3OTuwaTaOD2cgD9igJiPPflEVwnpVBLPJRX9eUJfBIccBcAdignO8pnOkh4x3I2zA69rUIf/KOOLzwiYe0/6co5U5UoZ7k
    WRITABLE_USER: AgCtJ+tVEBaZiOk35njIn0iR4/4YYbg20U1zkXpDFpN/n02ZNan207jLyv7HFS+3ZAKTy0zJnL95VX2FZl+avtTjHGaGWE2VjA0KkIWLUzKLeBH7i9lD8EVXuVKjU337fP9BLVIUK3q9F9GyV8xFjPjEWfkAatKBkt7XTuaFiLP0aIkHv5hGyN5DJa55uW+6ZGYUXZipfHqkvyBBsryFpmY9u0Os7FYSWiKJQIExu+B4BUDycrCuPRnetV0YXya/mDlhsY3UbWqL2GD/qnTv2wr7Wa5adiWqyQyGSAOOJl+6/r9hBsLrsOKge60bL8CH5uu41GS5WIkmQzdWwMMkF/O5kdvCrDivRoXNxtAjFA6Z991XGjfbcurUhYAepSoyZjUG2GS2SsXJzrEyGTYWF6R+Gg9o9CjYGswb9sMvGlVI78ndZ2JfGRfc38aOZIewYH/TzmF/kkq2q3hw3YYAALywtcHBY3fLSSlZcVbQa40ZE2wKczz08A0M4nFGMRojQpLcjeOu5qsKAGJsOlkCc8Cpmwr+eLmRDY3KS+Xm2TGIJtZSbkm+DubXbItlYH0cDXZcmVBY+hkPfrkqfxQ8GudxJ9mEA7uRyi/ll+vKGTv2n5REMe2p1KjjJrTXfNIrc85XJi/DYrnS3IeIDBIUM47K9S0XdSGRv16UzFnNEsiZ5tbhd/LJxjL0EimISlckLCgUwy+5
  template:
    metadata:
      name: mysql-app
      namespace: business
    type: Opaque
