---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-app
  namespace: data
spec:
  encryptedData:
    WRITABLE_PASSWORD: AgBUqAMpRvvdaiCiZEhaIMIZhuC1qSCu6IF+g6HgCdokXOCjheb8jZNWdiW6nOIOrmb9HP2tnou/ACbYXe/Z/voWp8NyLJNAQz0/joLmfy3InmKzzG5BNoNkuGphERq0S9vvOdlzvMlBeTg3Cu364HyAtHFTD1my7u7Refejgb7Z/HB/4FXCCnyUS4aoGxt4eLQ8GJT6C0Ll+F6bfieVi388oGY2mZNgZ38/gyQUd2Qrf67OIAbZXfkLGHbM7nX27CZyptsQ9aldgByXkeHiNxhaXPLQNIdAFCT74cx1jH2X7AKZzVVvXMi9hi75eHsstso6iWEf7xQIQ9CvHL/Sr3OcdLp8ZAJoAgpiraEs5yKaSXJ0Fw1Df/1H9OWiPLS6viu3K6vcuGjD4yp2TIoc5xtRks1E86jeqquS4lqXdRPA6Lcxc4klB0GnLP/dJ5oQ2LxxFE1DjdbPj9/H37c4XbKpoSlrXh7bJ81Un5h9hIamSaaNPbUTijGRbxNEPLRgav3XacbuCmi+KtYCW/Odd020vEUdsKIwDh5nrxd74D4A6/lQReMMAwOXAUe9O/OoyjX8fo6NUDOHIpMqrV/Cm9RRyrsP4zCAyeNaeldcT558ZHKPoTofcVY4CszzNQEh8FDRktN1rnaYyFfhL86jZ7trCQndVW0vEskx+WHwfsmpQ+G2Zbdw7OthARWdG2dTZvG0h7RU
    WRITABLE_USER: AgBZ4NKL42i9YhP2Nb2AXMIH5K57WmF24ZpvhiycxCYRO6aXaTTh/KW2/PEmaL3KVGhEabRUmJAfo0NYGaxwMqDJ61Pd34bQ6CTPm7ThB6IMJ6mxVkzRuUS7Pd4Uero5VSn1Kd9438oUz9U0t08nxJ8upWWP9DRN8y7hOHSmwOBFGZmn46LVOsr9L5EdvrYUuJ86TWZfv62w3cQ2yWpJyRnLgWP+y6PZy2fkxF9+j88Ji6Z06mIg1ZfT9ZxXMnNh16ltHcC26cIPZvfWNC7veQg8ThOIPmZOLy2EqPySzUKu46oD1Lm0RDu8LHVY92jk0Ie5sWGX2360/7fTifaijpAUFZ4KNQQaP3Wqb+ta5DK0xyhA2KqR/TPpsMT6AxDNWoN7TiPuKYe8BhAqdqjO9pRxd688dSxbkjY9D+7/dALhjTU208RmHmzb/Eh6B6tfdJ7k+DSUpkjtLFSIQrfgYCkT+n5BX1O+KVuGI2YrlaHMkhj3ewMAUFuy+5Q4s4T6xxk4wBBVbbaLzUQweOLeRX5F73mfk/2qunn7YBiNA8AEDuhjiF8adUDde2HBuXTXHbw3NlS5Y462o1G4CkgLrEiY/CA8/6EcUN6CO0ZB9vXuYIu5n8vgwdSmNoUY7jb3GYBZ2kDnfnqhbeEdj5api1yfopdgBNU5K9Qs98aOz2ay4OY5S8Q8f/jTLok0c//FAxTQyw68
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: business
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: business
      name: mysql-app
      namespace: data
    type: Opaque
