apiVersion: v1
kind: Secret
metadata:
  name: mysql-app-credentials
  namespace: business
  annotations:
    # Sursa: <namespace>/<nume-secret-moco>
    reflector.v1.k8s.emberstack.com/reflects: "data/moco-mysql"
type: Opaque
# Se lasă complet gol. Reflector va popula automat cheile în cluster.
data: {}