apiVersion: v1
kind: Secret
metadata:
  name: mysql-app-credentials # Îi poți da ce nume vrei tu în namespace-ul curent
  namespace: apps # Namespace-ul unde rulează aplicația ta
  annotations:
    reflector.stakater.com/reflects: "data/moco-mysql" # Sursa: <namespace>/<nume-secret-moco>
data: {} # Se lasă complet gol. Reflector va copia automat WRITABLE_USER, WRITABLE_PASSWORD, etc.