apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"

  datasource:
    name: Prometheus
    type: prometheus
    # Prometheus din kube-prometheus-stack (același namespace `monitoring`)
    url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: "30s"
      httpMethod: "POST"
