---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgAnOmrW0aTAIOhpEFviFmqyS6lVDk8traccbFDaTtgNxBkHUIy/W/WZdKfiUDbPmYGfFCZd4S3hCfxgGfdodcPf8WKP3TJxG0sQwpzoMgbiPYHvzIqBCHMYdwYH5FSUhuN/djeD3bIBPXN1oO5546rVmgm6hIInLJ7XrFFnHYkeAyzD18wyJA3TiANVvdrxUC2AXhydzGmSMJTyUuzAdBrFf8Br6+aC6LwG6yDv0ThTgMI2+3yVdJe70gRgC2958Z+S2Tde4bzmKzsVMzQ/IK8Nk5Pk5KprHA2O9mSICo1x4ntgypVRHEKwo0xZphXeRwIwvG5ux+IY7WzrY65sCYmIs8JoEERCiSvFeEJgrANA4R/LlpPYITgOPMd8Nzh4xMKTl9Lg5CdfcsV/23wEYHAPgQomkHwjYO/vCsN/+M7w5bSG2c0OCTPfGRhIaFR8bPyJU6LNkDAF1XmWQtIXEnaYmSArvoO5J0zqyzxfhWi82wQzYBfgeUK0q6GTJAhXxD0BcfvMqV29toUfMyC9Ea0BRszhQdKdaYaPeOmYcLgTTQhl7RYQZFFOTzsPnE3zejDRlpgyH15L7lbh8JDKUuHUHFBKYdvM88VUcr6YuePF7SKQ3nGKOFEtxXENEWAmSkEEDWKsiRDClDhTMYTQn3L8sX303FZWqXHBBXBPB9LqydoAugUXhK7GEpo/5k8taaK/dokpRw76MZcc2ICfjV1g7Q==
    GF_SECURITY_ADMIN_USER: AgBGMfld7N4eGW1UauhYCtcLdjIbysMZAHpwQ55VW3KlezZi7SUR5tvwys21QJ/8Q7UgFnY9Y018v3/4OW1f4Ea3b5HPWRR4gQhy9G+msHqK7YHWjoJQB4lBBfWJ5B18ySRrdz1mOnPn1RI2rct3TEc+EiCXJHXgcoVEpcFWV0QkDBi+y0ajzrs0cJaV3mDmbS8KZSguu4E0LqerIT2waV9lZpX09qN8mdrL0xx3DN/+G17ymRSnWOZT1UoO7X++bSFdNdhWWWAtsKS46RihjKglpR2L+I0DekRQY+cQX50KXbtUVpDXp6LtwoFtnLbRcHjBjWR/uJBqtI28c4LGy6JQ1zYUNhoN6QyaEd5/7N/hei3lb+qUnnT+ydlzJx0tjRkCoqFJC1h86x0638YFzCKukSc6SwHL2Od2L91X0goKmB69CkpTZIAJyjPTbTUFOF4TvNso55lW501QAejAwHGTLLtDRE2zPS+LLrH96jrtE+C7XfwaMR6u/r2tFmrLKo7VMZtSgQcFjIebxuRvjngEHhvFgIh6sL+3dmipG+z7HzjlSqDKC/+BkrO6r0JAzJMhanz4jjBj464UrQ4yDI+ILKZk8rpoU/xlz9b6RUfIHUaBfF9Kvt2lVEOtm0x3rmscTiozNRNzJQXbc+VFkWA15PwMMnUcBtEAKeY+4Fv9f2b0gEJE3BATzUcIl/HpCn7WlO3HEQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
