---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-keycloak
  namespace: business
spec:
  encryptedData:
    client-secret: AgC5AFbtbMk9YjlnYP1ZZwpxvyJeU104soF6PvGez1pk7xtcnJvaD2CVcrLI832eKR4xMwmNeoWdNXydO90Dw5/oTEd+1wviGsd11wA8DIakAljxJ+bo9d6VInpovQrQwhABOLMsdGwNTpMipowT1G7dBqALc0QtMw5GaS0q9b8nrcBgNq8X0c+mp9yvg/XVPJQxbN3gqPx0ipWwLIIgS7IHSAmr26fy4OTdgu29PoaAOBAP+c6D8+78+mYRCP2fJjbxzvxhRPJhYs/C84p4FpHXR+qEmPVls0MAx071cDHC4o5ybCP1KHOJuT44K+Lx13atMHP5dl+uIBMeBGae//Pu0gNKnnsxfUltMfZ8ppsHGNmK++JVm0JilBREi1RAiH6MhXl5ao/K03stXMAu4xYzbDYz9oKODfA5xTB+Gk2JVcHvuZbM04TJvgojg39FBkK+wKB1aXfZZTRoTzIyBtNdRC96bSqoV0Ap81rDM3yFIo530Fp785VeDPUKMV/E9miZssmkGSjZnDis05iM2ixKW/k5kpk+5Sr43MSZa8qt9BsTm0xTfdO8+ghy1mELNZFJKNHMSoA/S71fIPRkPATB5flItPm4aVG+kKrqqKrh+Hu1lrSy7A8v4X3qYuJprGYjoBArU3Mj78mlMOGnOL013W642mm6K04W/XagEt9bxUGrmVL0ShbweSKPL4B0DJfuFWZcxSwsV4HsnTyxEyBOJXqyq+MkIlJZGZagd+NKPX1II6ygHq4mg+YBiA==
    cookie-secret: AgAlwJmUrL2aFxDDjbpL7IMWKzdMXs8grG2YKMpRL5RSKT28poIQtu2lY5i5f/g/qesvDTRghsqMbCIguJTHSOry1SiqDrTijoq2kdQghn5daOlJ22G8rfTOD2ZF/w5kchPVldfPRpbix6AHQVeC3Uf10kHlSeG8SC0DtG2tVI9jd4l7s2Zs+2aYqGxnw9QsH/5Ni84EJzRMfc37Oz+gkKYNcq6TqrX2edV2LrA2OWVXltR4q3ntZbG5/s3EHyRl5yoZaeDApdbcY5ra9O/ZB8fxyAxPC3uJ7PkPe0btcqkF4cS/4lxBd1c4ZkMWOcntugLJGkSldLFvQKgJeqRWy0CZqLLBha764MmWWo5tyvPnBOklOBlezJhq0FjQ6dFIQccfrcbTVkxhZkebXzN/+xLUFJe8U4zVLIkURXayLGsTYnwt3BCumc2+pnK8b9omajfzJgQaAyzfOcX+Ye11TwIrtB/YIn8Qqe2PpZexmlvmpTkK/UM+KNO3Tdc6Y+820wHjzMWmWo1Yr/lBMBuIGLxe0RmWr56/CN2oZP+glL4G4QL6VfQE9yR2iFs015Y5SO3bPlOOgmxjcBVYYM67FN3aDw/b3fujRUvypGO9BSAa4+CE/a4PjgeFebwhvEX5nYHnTONq1av5QfB5eth4ODlNpbBPj3lSH2DyYb5IMdzou9kFMhP4qbyLiZ9pNB8m65ahfHXG9UEmAaNLafnKl1Y9gi1ESEdepTx0FYPix97xSA==
  template:
    metadata:
      name: oauth2-proxy-keycloak
      namespace: business
