---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBToHXGvueYklXG+uBcvkW0Nif7GLtBVyvwwGoc7AsL3EVMY5B1vpfulf7txp2B8GRx4epK3NjuhZIeHK5mLFVDU7sMUvrf19HSPBvfdehgBbqVei9Z361fo+O1CRF+lpHLfu+d93l38L9ox1ZU7FmRCEzClEWI1KKO53gYOozTNrzrQNKvNBog5rluV/pnSdMVx+69LcqXm3bNw3ZwJMbW8EtIdYln5DBERDT+3K0Zc4BEgBpS1H+8UGv8TRMt+LN81hRGOHa70QxcEKSgPYe26ygEVJCz0OZtlZz7h8YilcWnRm2yE6ko3AkZ3lYzcuhtJ4QE905/0QDhK/WxE823kv8EwlckXay69IVTDU+jRStuoenyN39q6H/rOsXL179uKmYZ8fREW0XvoaZt0PNfh0Nu+IosLNZMGGEHaC3uqqSPkZWI/Bt/NXcSWz9qf07lGi2MoRmOsxMCa8gdyFESIBuV08GRCI0zcSzmixHADjwNl4rtnOtCYdwaHPDUPI/wBP5rB4XTGgOPcP8/Pav6TV94Zo47Hf8smLMs2r5/09CjbvSUD4dqE8crSOs4ZvmoYAx+QeePhSYSSaq94/IDeCrVFtP1dIID/2jY6GFTQEmvQqdxowDM66t978qp9/8fqfWsCiWw0eqxXeIuBrNiHtjUdJLmYRu3v9lzRVgb/eSOSHFQkcSzURluz+D/aS0nWO9XDzcAzebGga/CoRjHZA==
    admin-user: AgCQV2K7/PdMVfZrs5SGSeSssXjTcLwm8+WuAsucm8HEH/XFAHIMcgbUkK9QDJKEFqxMXIoxLiEJNyP8v8O9IkPdCdcDQhKzDnRzHZuCNuIv/cy1kg04/GaBw19RZBJpuL1Uthd9rWR8Z7T3oHuhRZ/X/GInDvxWxSYilBfNhDb4vtOgrxdExmv6sfquWxA1KVLgYW4qup0P9Y+Gt39aiGwMB+HWs9TqI1Htc6Z9k37Y/Mf1g4LVHRN0PdISteRb7QmpAx75lTspT6IgPWycds4UN6aEcZtkRi4ksMgBAVE0nasEp9iCEU8FrnkDVsDHqY6VSzcDoY8CD3g9dPy2hY8TE8wRUzS35AuoJsuzZ3uJAbNbCu7fGwF4fNv7WmI23w4YebpB3hKmELdxOPvKLQsutBSZCezuaJDaGIFtDtEIg5/jAJ5sK2pyO5gmsKWUEbkGp7oB+7MHDMCwVPmdiRPwUd00VfxDuDfFLUqY1M2ZgmcEcrqWG/tEaEtJFo1sYcoWNrcZWfB0FTKzoTTG4ghscLFEcYJGEykK/olwEf53Ptla6bMmT9zpen8J+7zI49mnm6mrfnxcFIxImIn/HfFsmPoqQOvkgeELJb2m6H24I85fjtKO6rRYfhnOUK1vLht4cn2IeMvwUrH/k9bteTGEonVQ8V55YIQxEsWrlooqx/Z5I09lcDnZAivN8LWaG94LHiM9FA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque