apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://github.com/nimigeanconstantinion/ms-gitops.git
      targetRevision: master
      path: business/charts/microservice
      helm:
        releaseName: data-service
        valueFiles:
          - $values/business/data-service/values.yaml

    - repoURL: https://github.com/nimigeanconstantinion/ms-gitops.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: microserv-products

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true