apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  annotations:
    # wave 2: CR-urile se aplica DUPA ce operatorul Strimzi (wave 0) a instalat CRD-urile.
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/nimigeanconstantinion/ms-gitops.git
    targetRevision: master
    path: infra/kafka
    # recurse: include si subfolderul topics/ (KafkaTopic-urile).
    # Lectia de la data layer: un folder de Application e citit NON-recursiv implicit.
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: messaging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true