apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/nimigeanconstantinion/ms-gitops.git
    targetRevision: master
    path: infra/postgres-keycloak

  destination:
    server: https://kubernetes.default.svc
    namespace: data

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
