apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
spec:
  project: default

  sources:
    # Sursa 1: Helm chart oficial Sealed Secrets
    - repoURL: https://bitnami.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.16.2
      helm:
        releaseName: sealed-secrets-controller
        valueFiles:
          - $values/infra/sealed-secrets/values.yaml

    # Sursa 2: values overrides din acest repo
    - repoURL: https://github.com/nimigeanconstantinion/ms-gitops.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
