apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://github.com/nimigeanconstantinion/ms-gitops.git
          targetRevision: master
          path: infra/keycloak
          directory:
            recurse: true

    # 2. Sursa nouă pentru realm-ul de business
      # ArgoCD va citi de aici fișierul rsk-realm.yaml
    - repoURL: https://github.com/nimigeanconstantinion/ms-gitops.git
      targetRevision: master
      path: business/rsk/keycloak
      directory:
        recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: auth

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
